# Generated by Django 4.2.7 on 2023-11-27 21:19

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.list


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Статус задачи')),
            ],
            options={
                'verbose_name': 'Статус задачи',
                'verbose_name_plural': 'Статусы задач',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Избранное')),
                ('mark', models.BooleanField(default=False, verbose_name='Отметить')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритет',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('completed_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taskmanager.category', verbose_name='Категория')),
                ('completed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taskmanager.completed', verbose_name='Статус задачи')),
                ('favourite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taskmanager.favourite', verbose_name='Избранное')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='taskmanager.priority', verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['completed_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteTask',
            fields=[
                ('taskmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskmanager.taskmanager')),
            ],
            bases=('taskmanager.taskmanager', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='FinishTask',
            fields=[
                ('taskmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskmanager.taskmanager')),
            ],
            bases=('taskmanager.taskmanager', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='TagDelete',
            fields=[
                ('taskmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskmanager.taskmanager')),
            ],
            bases=('taskmanager.taskmanager', django.views.generic.list.ListView),
        ),
        migrations.CreateModel(
            name='TaskUpdate',
            fields=[
                ('taskmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='taskmanager.taskmanager')),
            ],
            bases=('taskmanager.taskmanager', django.views.generic.list.ListView),
        ),
    ]
