# Generated by Django 4.2.7 on 2023-11-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_alter_user_is_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
