# Generated by Django 4.2.7 on 2023-11-28 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0004_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmanager',
            name='user',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
