# Generated by Django 4.2.7 on 2023-11-28 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taskmanager', '0012_remove_taskmanager_user_taskmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='user',
            field=models.ForeignKey(auto_created=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
