# Generated by Django 4.2.7 on 2023-11-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0015_alter_taskmanager_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmanager',
            name='user',
        ),
    ]
